services:
  db:
    image: postgres:16-alpine
    container_name: family_db_dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: family_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: myfamily_minio_dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: myfamily_admin
      MINIO_ROOT_PASSWORD: myfamily_dev_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - myfamily_minio_data:/data
volumes:
  postgres_data:
  myfamily_minio_data:
    external: true
